from __future__ import annotations

from typing import Any, Dict, Optional, Protocol


class WebDataExtractorPort(Protocol):
    def busca_publica_disponivel(self) -> bool: ...

    async def buscar_urls_publicas(self, *args: Any, **kwargs: Any): ...

    async def buscar_urls_google(self, *args: Any, **kwargs: Any): ...

    async def coletar_conteudo_pagina_playwright(self, *args: Any, **kwargs: Any): ...

    def extrair_texto_principal_com_trafilatura(self, *args: Any, **kwargs: Any): ...

    def extrair_metadados_estruturados(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...

    def normalizar_dados_de_metadados(
        self,
        metadata_bruta: Dict[str, Any],
    ) -> Dict[str, Any]: ...

    async def extrair_dados_produto_com_llm(self, *args: Any, **kwargs: Any): ...

    async def extract_relevant_data_from_url(self, *args: Any, **kwargs: Any): ...

    def extract_text_from_image_region(self, image_bytes: bytes): ...
