FROM python:3.11-slim
WORKDIR /app
COPY requirements-backend.txt .
RUN pip install --no-cache-dir -r requirements-backend.txt
COPY . .
ENV FIRST_SUPERUSER_EMAIL="admin@example.com" \
    FIRST_SUPERUSER_PASSWORD="adminpass" \
    ADMIN_EMAIL="admin@example.com" \
    ADMIN_PASSWORD="adminpass"
CMD ["pytest"]
