"""Adiciona a coluna resultado_json na tabela catalog_import_files

Revision ID: 5360b07baba0
Revises: 999999999999
Create Date: 2025-06-23 17:37:06.942829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5360b07baba0'
down_revision: Union[str, None] = '999999999999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_planos_id', table_name='planos')
    op.drop_index('ix_planos_nome', table_name='planos')
    op.drop_table('planos')
    op.drop_index('ix_attribute_templates_id', table_name='attribute_templates')
    op.drop_table('attribute_templates')
    op.drop_index('ix_fornecedor_import_jobs_id', table_name='fornecedor_import_jobs')
    op.drop_table('fornecedor_import_jobs')
    op.drop_index('ix_produtos_ean', table_name='produtos')
    op.drop_index('ix_produtos_id', table_name='produtos')
    op.drop_index('ix_produtos_sku', table_name='produtos')
    op.drop_index('ix_produtos_user_id_ean', table_name='produtos')
    op.drop_index('ix_produtos_user_id_nome_base', table_name='produtos')
    op.drop_index('ix_produtos_user_id_sku', table_name='produtos')
    op.drop_table('produtos')
    op.drop_index('ix_fornecedores_id', table_name='fornecedores')
    op.drop_index('ix_fornecedores_nome', table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index('ix_product_types_global_key_name_unique', table_name='product_types', postgresql_where='(user_id IS NULL)')
    op.drop_index('ix_product_types_id', table_name='product_types')
    op.drop_index('ix_product_types_user_id_key_name', table_name='product_types')
    op.drop_table('product_types')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_nome_completo', table_name='users')
    op.drop_index('ix_users_reset_password_token', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_registros_historico_id', table_name='registros_historico')
    op.drop_table('registros_historico')
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_catalog_import_files_id', table_name='catalog_import_files')
    op.drop_table('catalog_import_files')
    op.drop_index('ix_registros_uso_ia_id', table_name='registros_uso_ia')
    op.drop_table('registros_uso_ia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_uso_ia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_acao', postgresql.ENUM('CRIACAO_TITULO_PRODUTO', 'CRIACAO_DESCRICAO_PRODUTO', 'ENRIQUECIMENTO_WEB_PRODUTO', 'OTIMIZACAO_SEO_CONTEUDO', 'GERACAO_TAGS_PRODUTO', 'ANALISE_SENTIMENTO_REVIEWS', 'TRADUCAO_CONTEUDO_PRODUTO', 'SUMARIZACAO_CARACTERISTICAS', 'SUGESTAO_ATRIBUTOS_GEMINI', 'OUTRO', 'CRIACAO_PRODUTO', name='tipoacaoenum'), autoincrement=False, nullable=False),
    sa.Column('provedor_ia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modelo_ia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prompt_utilizado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resposta_ia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tokens_prompt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens_resposta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custo_estimado_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('creditos_consumidos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detalhes_erro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name='registros_uso_ia_produto_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='registros_uso_ia_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='registros_uso_ia_pkey')
    )
    op.create_index('ix_registros_uso_ia_id', 'registros_uso_ia', ['id'], unique=False)
    op.create_table('catalog_import_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stored_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'UPLOADED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('result_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pages_processed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name='catalog_import_files_fornecedor_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='catalog_import_files_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='catalog_import_files_pkey')
    )
    op.create_index('ix_catalog_import_files_id', 'catalog_import_files', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=True)
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.create_table('registros_historico',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entidade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('acao', postgresql.ENUM('CRIACAO', 'ATUALIZACAO', 'DELECAO', name='tipoacaosistemaenum'), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detalhes_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='registros_historico_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='registros_historico_pkey')
    )
    op.create_index('ix_registros_historico_id', 'registros_historico', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nome_completo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idioma_preferido', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plano_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chave_openai_pessoal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chave_google_gemini_pessoal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('limite_produtos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limite_enriquecimento_web', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limite_geracao_ia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_expiracao_plano', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reset_password_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reset_password_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], name='users_plano_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='users_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user_id'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_reset_password_token', 'users', ['reset_password_token'], unique=False)
    op.create_index('ix_users_nome_completo', 'users', ['nome_completo'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('product_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('key_name', sa.VARCHAR(), autoincrement=False, nullable=False, comment="Chave única para identificar o tipo, ex: 'smartphones'"),
    sa.Column('friendly_name', sa.VARCHAR(), autoincrement=False, nullable=False, comment="Nome amigável, ex: 'Smartphones'"),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Se NULL, é um tipo global/padrão. Senão, pertence a um usuário.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='product_types_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_types_pkey'),
    sa.UniqueConstraint('user_id', 'key_name', name='_user_key_name_uc'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_product_types_user_id_key_name', 'product_types', ['user_id', 'key_name'], unique=False)
    op.create_index('ix_product_types_id', 'product_types', ['id'], unique=False)
    op.create_index('ix_product_types_global_key_name_unique', 'product_types', ['key_name'], unique=True, postgresql_where='(user_id IS NULL)')
    op.create_table('fornecedores',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('fornecedores_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_contato', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefone_contato', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('site_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('termos_contratuais', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contato_principal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link_busca_padrao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('default_column_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fornecedores_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fornecedores_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_fornecedores_nome', 'fornecedores', ['nome'], unique=False)
    op.create_index('ix_fornecedores_id', 'fornecedores', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_base', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nome principal/original do produto'),
    sa.Column('nome_chat_api', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Nome otimizado/gerado pela IA'),
    sa.Column('descricao_original', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descricao_chat_api', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ean', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('ncm', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('marca', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('preco_custo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('preco_venda', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('margem_lucro', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estoque_disponivel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peso_gramas', sa.INTEGER(), autoincrement=False, nullable=True, comment='Peso em gramas'),
    sa.Column('dimensoes_cm', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Formato AxLxP, ex: 10x15x20'),
    sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria_original', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('categoria_mapeada', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('tags_palavras_chave', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('imagem_principal_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imagens_secundarias_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_enriquecimento_web', postgresql.ENUM('NAO_INICIADO', 'PENDENTE', 'EM_PROGRESSO', 'CONCLUIDO', 'FALHA', 'NAO_APLICAVEL', 'FALHOU', 'FALHA_API_EXTERNA', 'FALHA_CONFIGURACAO_API_EXTERNA', 'CONCLUIDO_SUCESSO', 'CONCLUIDO_COM_DADOS_PARCIAIS', 'NENHUMA_FONTE_ENCONTRADA', name='statusenriquecimentoenum'), autoincrement=False, nullable=True),
    sa.Column('status_titulo_ia', postgresql.ENUM('NAO_INICIADO', 'PENDENTE', 'EM_PROGRESSO', 'CONCLUIDO', 'FALHA', 'NAO_APLICAVEL', name='statusgeracaoiaenum'), autoincrement=False, nullable=True),
    sa.Column('status_descricao_ia', postgresql.ENUM('NAO_INICIADO', 'PENDENTE', 'EM_PROGRESSO', 'CONCLUIDO', 'FALHA', 'NAO_APLICAVEL', name='statusgeracaoiaenum'), autoincrement=False, nullable=True),
    sa.Column('dados_brutos_web', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON com dados extraídos da web (textos, metadados)'),
    sa.Column('dynamic_attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Atributos dinâmicos preenchidos baseados no ProductType (JSON)'),
    sa.Column('log_processamento', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Lista de mensagens/eventos de log para este produto'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('log_enriquecimento_web', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name='produtos_fornecedor_id_fkey'),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], name='produtos_product_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='produtos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='produtos_pkey'),
    sa.UniqueConstraint('user_id', 'ean', name='uq_produtos_user_ean'),
    sa.UniqueConstraint('user_id', 'sku', name='uq_produtos_user_sku')
    )
    op.create_index('ix_produtos_user_id_sku', 'produtos', ['user_id', 'sku'], unique=False)
    op.create_index('ix_produtos_user_id_nome_base', 'produtos', ['user_id', 'nome_base'], unique=False)
    op.create_index('ix_produtos_user_id_ean', 'produtos', ['user_id', 'ean'], unique=False)
    op.create_index('ix_produtos_sku', 'produtos', ['sku'], unique=False)
    op.create_index('ix_produtos_id', 'produtos', ['id'], unique=False)
    op.create_index('ix_produtos_ean', 'produtos', ['ean'], unique=False)
    op.create_table('fornecedor_import_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'REVIEW'::character varying"), autoincrement=False, nullable=False),
    sa.Column('result_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fornecedor_import_jobs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fornecedor_import_jobs_pkey')
    )
    op.create_index('ix_fornecedor_import_jobs_id', 'fornecedor_import_jobs', ['id'], unique=False)
    op.create_table('attribute_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_key', sa.VARCHAR(), autoincrement=False, nullable=False, comment="Chave do atributo, ex: 'cor', 'memoria_ram'"),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False, comment="Nome de exibição do atributo, ex: 'Cor', 'Memória RAM'"),
    sa.Column('field_type', postgresql.ENUM('TEXT', 'NUMBER', 'BOOLEAN', 'SELECT', 'MULTISELECT', 'DATE', 'TEXTAREA', name='attributefieldtypeenum'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Ajuda sobre o atributo'),
    sa.Column('default_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment="Lista de opções para select/multiselect, armazenada como JSON: ['Op1', 'Op2']"),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_filterable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], name='attribute_templates_product_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attribute_templates_pkey'),
    sa.UniqueConstraint('product_type_id', 'attribute_key', name='_product_type_attribute_key_uc')
    )
    op.create_index('ix_attribute_templates_id', 'attribute_templates', ['id'], unique=False)
    op.create_table('planos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preco_mensal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('limite_produtos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limite_enriquecimento_web', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limite_geracao_ia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permite_api_externa', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('suporte_prioritario', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planos_pkey')
    )
    op.create_index('ix_planos_nome', 'planos', ['nome'], unique=True)
    op.create_index('ix_planos_id', 'planos', ['id'], unique=False)
    # ### end Alembic commands ###

