"""Backup

Revision ID: 71136158c1ff
Revises: 
Create Date: 2025-06-24 12:12:49.015430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71136158c1ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class _MigrationEntries:
    @staticmethod
    def upgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
        pass
        # ### end Alembic commands ###

    @staticmethod
    def downgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
        pass
        # ### end Alembic commands ###


upgrade = _MigrationEntries.upgrade
downgrade = _MigrationEntries.downgrade

