"""Add media and log fields to Product model

Revision ID: 8052d919e969
Revises: 
Create Date: 2025-06-04 20:50:57.817740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8052d919e969'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attribute_templates_attribute_key'), 'attribute_templates', ['attribute_key'], unique=False)
    op.add_column('planos', sa.Column('data_expiracao_plano', sa.DateTime(timezone=True), nullable=True))
    op.add_column('planos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('planos', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('planos', 'preco_mensal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('planos', 'limite_produtos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('planos', 'limite_enriquecimento_web',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('planos', 'limite_geracao_ia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('planos', 'permite_api_externa',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('planos', 'suporte_prioritario',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('product_types', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_product_types_key_name', table_name='product_types')
    op.create_index(op.f('ix_product_types_key_name'), 'product_types', ['key_name'], unique=True)
    op.add_column('produtos', sa.Column('imagens_produto', sa.JSON(), nullable=True))
    op.add_column('produtos', sa.Column('videos_produto', sa.JSON(), nullable=True))
    op.add_column('produtos', sa.Column('log_enriquecimento_web', sa.JSON(), nullable=True))
    op.add_column('produtos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('produtos', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('produtos', 'status_enriquecimento_web',
               existing_type=postgresql.ENUM('NAO_INICIADO', 'PENDENTE', 'EM_PROGRESSO', 'CONCLUIDO', 'FALHA', name='statusenriquecimentoenum'),
               nullable=False)
    op.alter_column('produtos', 'status_titulo_ia',
               existing_type=postgresql.ENUM('NAO_INICIADO', 'PENDENTE', 'EM_PROGRESSO', 'CONCLUIDO', 'FALHA', 'NAO_APLICAVEL', name='statusgeracaoiaenum'),
               nullable=False)
    op.alter_column('produtos', 'status_descricao_ia',
               existing_type=postgresql.ENUM('NAO_INICIADO', 'PENDENTE', 'EM_PROGRESSO', 'CONCLUIDO', 'FALHA', 'NAO_APLICAVEL', name='statusgeracaoiaenum'),
               nullable=False)
    op.drop_index('ix_produtos_categoria_mapeada', table_name='produtos')
    op.drop_index('ix_produtos_categoria_original', table_name='produtos')
    op.drop_index('ix_produtos_ean', table_name='produtos')
    op.drop_index('ix_produtos_marca', table_name='produtos')
    op.drop_index('ix_produtos_modelo', table_name='produtos')
    op.drop_index('ix_produtos_ncm', table_name='produtos')
    op.drop_index('ix_produtos_nome_chat_api', table_name='produtos')
    op.drop_index('ix_produtos_sku', table_name='produtos')
    op.create_index(op.f('ix_produtos_sku'), 'produtos', ['sku'], unique=True)
    op.drop_column('produtos', 'imagem_principal_url')
    op.drop_column('produtos', 'data_atualizacao')
    op.drop_column('produtos', 'imagens_secundarias_urls')
    op.drop_column('produtos', 'data_criacao')
    op.add_column('registros_uso_ia', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('registros_uso_ia', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_registros_uso_ia_timestamp', table_name='registros_uso_ia')
    op.drop_column('registros_uso_ia', 'timestamp')
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_nome_completo', table_name='users')
    op.drop_index('ix_users_provider_user_id', table_name='users')
    op.drop_index('ix_users_reset_password_token', table_name='users')
    op.create_unique_constraint(None, 'users', ['provider_user_id'])
    op.drop_column('users', 'reset_password_token_expires_at')
    op.drop_column('users', 'reset_password_token')
    op.drop_column('users', 'data_expiracao_plano')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_expiracao_plano', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_password_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_password_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_reset_password_token', 'users', ['reset_password_token'], unique=True)
    op.create_index('ix_users_provider_user_id', 'users', ['provider_user_id'], unique=True)
    op.create_index('ix_users_nome_completo', 'users', ['nome_completo'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.add_column('registros_uso_ia', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index('ix_registros_uso_ia_timestamp', 'registros_uso_ia', ['timestamp'], unique=False)
    op.drop_column('registros_uso_ia', 'updated_at')
    op.drop_column('registros_uso_ia', 'created_at')
    op.add_column('produtos', sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('produtos', sa.Column('imagens_secundarias_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('data_atualizacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('imagem_principal_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_produtos_sku'), table_name='produtos')
    op.create_index('ix_produtos_sku', 'produtos', ['sku'], unique=False)
    op.create_index('ix_produtos_nome_chat_api', 'produtos', ['nome_chat_api'], unique=False)
    op.create_index('ix_produtos_ncm', 'produtos', ['ncm'], unique=False)
    op.create_index('ix_produtos_modelo', 'produtos', ['modelo'], unique=False)
    op.create_index('ix_produtos_marca', 'produtos', ['marca'], unique=False)
    op.create_index('ix_produtos_ean', 'produtos', ['ean'], unique=False)
    op.create_index('ix_produtos_categoria_original', 'produtos', ['categoria_original'], unique=False)
    op.create_index('ix_produtos_categoria_mapeada', 'produtos', ['categoria_mapeada'], unique=False)
    op.alter_column('produtos', 'status_descricao_ia',
               existing_type=postgresql.ENUM('NAO_INICIADO', 'PENDENTE', 'EM_PROGRESSO', 'CONCLUIDO', 'FALHA', 'NAO_APLICAVEL', name='statusgeracaoiaenum'),
               nullable=True)
    op.alter_column('produtos', 'status_titulo_ia',
               existing_type=postgresql.ENUM('NAO_INICIADO', 'PENDENTE', 'EM_PROGRESSO', 'CONCLUIDO', 'FALHA', 'NAO_APLICAVEL', name='statusgeracaoiaenum'),
               nullable=True)
    op.alter_column('produtos', 'status_enriquecimento_web',
               existing_type=postgresql.ENUM('NAO_INICIADO', 'PENDENTE', 'EM_PROGRESSO', 'CONCLUIDO', 'FALHA', name='statusenriquecimentoenum'),
               nullable=True)
    op.drop_column('produtos', 'updated_at')
    op.drop_column('produtos', 'created_at')
    op.drop_column('produtos', 'log_enriquecimento_web')
    op.drop_column('produtos', 'videos_produto')
    op.drop_column('produtos', 'imagens_produto')
    op.drop_index(op.f('ix_product_types_key_name'), table_name='product_types')
    op.create_index('ix_product_types_key_name', 'product_types', ['key_name'], unique=False)
    op.alter_column('product_types', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('planos', 'suporte_prioritario',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('planos', 'permite_api_externa',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('planos', 'limite_geracao_ia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('planos', 'limite_enriquecimento_web',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('planos', 'limite_produtos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('planos', 'preco_mensal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('planos', 'updated_at')
    op.drop_column('planos', 'created_at')
    op.drop_column('planos', 'data_expiracao_plano')
    op.drop_index(op.f('ix_attribute_templates_attribute_key'), table_name='attribute_templates')
    # ### end Alembic commands ###
