"""add_import_quality_score_to_produto

Revision ID: a028b2cbb145
Revises: 0d5dcb0b6f61
Create Date: 2026-03-17 22:18:35.195014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a028b2cbb145'
down_revision: Union[str, None] = '0d5dcb0b6f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attribute_templates', 'collect_in_ai',
               existing_type=sa.BOOLEAN(),
               comment='Indica se este atributo deve orientar coleta e sugestoes no modo IA.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('produtos', sa.Column('import_quality_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_users_nome_empresa'), 'users', ['nome_empresa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nome_empresa'), table_name='users')
    op.drop_column('produtos', 'import_quality_score')
    op.alter_column('attribute_templates', 'collect_in_ai',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica se este atributo deve orientar coleta e sugestoes no modo IA.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###

