from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class FileProcessingPort(Protocol):
    async def save_uploaded_catalog(self, *args: Any, **kwargs: Any): ...

    def delete_catalog_file(self, *args: Any, **kwargs: Any): ...

    def get_file_path_by_id(self, *args: Any, **kwargs: Any): ...

    async def processar_arquivo_excel(self, *args: Any, **kwargs: Any): ...

    async def processar_arquivo_csv(self, *args: Any, **kwargs: Any): ...

    async def processar_arquivo_pdf(self, *args: Any, **kwargs: Any): ...

    async def preview_arquivo_excel(self, *args: Any, **kwargs: Any): ...

    async def preview_arquivo_csv(self, *args: Any, **kwargs: Any): ...

    async def preview_arquivo_pdf(self, *args: Any, **kwargs: Any): ...

    async def gerar_preview(self, *args: Any, **kwargs: Any): ...

    async def pdf_bytes_to_images(self, *args: Any, **kwargs: Any): ...

    def pdf_pages_to_images(self, *args: Any, **kwargs: Any): ...

    async def extrair_pagina_pdf(self, *args: Any, **kwargs: Any): ...

    def generate_pdf_page_images(self, *args: Any, **kwargs: Any): ...

    def extract_pdf_region_image(self, *args: Any, **kwargs: Any): ...

    def parse_annotation_to_dataframe(self, *args: Any, **kwargs: Any): ...

    def extract_data_from_pdf_region(self, *args: Any, **kwargs: Any): ...

    async def process_pdf_job(
        self,
        job_id: int,
        pdf_path: str,
        start_page: int = 1,
        mapping: Optional[Dict[str, str]] = None,
    ) -> None: ...

    def extract_data_from_single_page(self, file_path: str, page_number: int) -> Dict[str, Any]: ...

    def processar_linha_padronizada(
        self,
        row: Dict[str, Any],
        mapeamento_colunas_usuario: Optional[Dict[str, str]],
    ) -> Dict[str, Any]: ...
