name: Python tests

on:
  push:
    paths:
      - '**.py'
      - 'requirements-backend.txt'
      - '.github/workflows/python-tests.yml'
      - 'tests/**'
  pull_request:
    paths:
      - '**.py'
      - 'requirements-backend.txt'
      - '.github/workflows/python-tests.yml'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build test image
        run: docker build -f Dockerfile.test -t catalogai-test .
      - name: Run tests
        run: docker run --rm catalogai-test
